blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/tscritch/wavesurfer-record-plugin-wav/discussions
    about: Please discuss non bug-related topics there
